name: CI

on:
    push:

env:
    CI: true

jobs:
    check-spelling:
        name: Check spelling
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: marshallku/actions/analyze/spell@master
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: marshallku/actions/setup/pnpm@master
            - name: Build
              run: pnpm build
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: marshallku/actions/setup/pnpm@master
            - name: Test
              run: pnpm test
    sonarqube:
        name: Analyze with SonarQube
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/master'
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - uses: marshallku/actions/setup/pnpm@master
            - name: Test
              run: pnpm test
            - uses: sonarsource/sonarqube-scan-action@v2
              env:
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
                  SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
